### ISSUE TITLE
TSLint Source Actions Missing

### ISSUE THREAD

**Issue by chris-t-reilly** [microsoft/vscode-typescript-tslint-plugin#100] opened 2019-06-12 12:04 UTC
No Source Actions are being shown when calling Source Action on a line that fails a tslint check with a "has-fix" (missing semi-colons for example).

Version: 1.35.0 (system setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

[![](http://img.youtube.com/vi/M5exi16mz5U/0.jpg)](http://www.youtube.com/watch?v=M5exi16mz5U "Youtube Video")

**Comment by cruhl** [comment] 2019-06-13 16:18
I am having the same issue

**Comment by cruhl** [comment] 2019-06-13 16:20
![image](https://user-images.githubusercontent.com/4983357/59449711-347e1100-8dcd-11e9-8c86-5229d22acdcc.png)

**Comment by cruhl** [comment] 2019-06-13 16:20
^ Shows the warning, but no source actions...

**Comment by cruhl** [comment] 2019-06-13 16:20
![image](https://user-images.githubusercontent.com/4983357/59449745-4cee2b80-8dcd-11e9-95c3-b99f36753cd8.png)

**Comment by cruhl** [comment] 2019-06-13 16:23
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:19:05.197Z
Node.js: v12.4.0
OS: Mac OSX Mojave 10.14.1 (18B75)

**Comment by AndreasCag** [comment] 2019-06-16 18:19
Ran into same issue when tried to configure auto fix on save

**Comment by mjbvz** [comment] 2019-06-17 22:56
Duplicate of #51

Try with extension version 1.2.0

**Closed by mjbvz** 2019-06-17 22:56 UTC

**Comment by Lordmau5** [comment] 2019-09-05 18:57
I'm running version v1.2.2 and I don't have any source actions available, only "Optimize Imports".

Even with the deprecated package it doesn't work.

Did a new VS Code update or TSLint plugin break it?

```Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362```
