### ISSUE TITLE
error message in node_modules

### ISSUE THREAD

**Issue by JounQin** [Microsoft/vscode-typescript-tslint-plugin#18] opened 2018-11-07 14:31 UTC
```
[tslint]
Failed to load the TSLint library for the document /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts
To use TSLint for single file install tslint globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen VS Code after installing tslint.
```

My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "lib": ["esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "target": "esnext"
  }
}
```

And I've uninstalled `vscode-tslint` plugin and tried to install `typescript` and `tslint` globally, but it still emits errors.

**Comment by justingrant** [comment] 2018-12-06 20:20
@JounQin - I think this error message is not fully accurate. I got the same error in my project, and I fixed it via `npm install -D tslint` in my project folder (not globally) and the error went away.

**Comment by mjbvz** [comment] 2018-12-13 01:58
Duplicate of #26

**Closed by mjbvz** 2018-12-13 01:58 UTC

**Comment by JounQin** [comment] 2018-12-14 13:44
@mjbvz Are you sure? I'm facing a lot of warnings from `.d.ts` in `node_modules` directory...

![image](https://user-images.githubusercontent.com/8336744/50006652-657db480-ffe9-11e8-832b-44316ac639a8.png)

**Comment by mjbvz** [comment] 2018-12-15 00:42
Different error, it should not lint `d.ts` files by default: https://github.com/Microsoft/typescript-tslint-plugin/issues/41

**Comment by JounQin** [comment] 2018-12-15 01:47
What about `.ts` source codes in `node_modules`? It should only not lint all `.ts ` files in `node_modules`. And also user customed `.d.ts` files should also be linted.

Beside, why not read it from `exclude` of `tsconfig.json` or `linterOptions.exclude` of `tslint.json`?

**Comment by glen-84** [comment] 2019-01-08 18:02
@JounQin I've just opened #40.
