### ISSUE TITLE
Memory leakage?

### ISSUE THREAD

**Issue by CN91** [microsoft/vscode-typescript-tslint-plugin#129] opened 2020-03-04 11:36 UTC
I am experiencing high memory usage caused by the language features for js/tslint only existing when I use the tslint plugin. Disabling the tslint extension did seem to solve the problem and also the language features itself seamed very slow (during ng serve).

It eats up my entire memory of 32gb on windows 10.

 code --status

Version:          Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)
Memory (System):  31.88GB (0.33GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        enabled
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       78   21976  code main
    5      218   16208     window (workflow.component.ts - workflow - Visual Studio Code)
    0       33    1656       searchService
    0        6   12024       winpty-process
    0       64    3324         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0        3   18976           C:\WINDOWS\system32\cmd.exe /c ""C:\Users\nibberingc\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --status"
    0       34   10376             electron_node cli.js
    0       58   17716               "C:\Users\nibberingc\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
    3       11    2524                 gpu-process
    2        3   19380                 utility
    0        9   22764         console-window-host (Windows internal process)
    0        6   16856       winpty-process
    0        9    1784         console-window-host (Windows internal process)
    0       63   16100         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0        3   10976           C:\WINDOWS\system32\cmd.exe /c ""C:\Users\nibberingc\AppData\Roaming\npm\ng.cmd" serve"
    0      463    8112             "node"   "C:\Users\nibberingc\AppData\Roaming\npm\\node_modules\@angular\cli\bin\ng" serve
    0      186    4036               "C:\Program Files\nodejs\node.exe" C:\Users\nibberingc\Workspace\workflow\node_modules\@ngtools\webpack\src\type_checker_worker.js 9d93e901-158a-4cf9-ba1b-2f0582ffcfeb
    0       15   24248       watcherService
    0        9   21596         console-window-host (Windows internal process)
    0       95   24780       extensionHost
    0       47    1444         "C:\Program Files\WSO2\Enterprise Integrator\6.5.0\jdk\jdk8u212-b03\bin\java" -DwatchParentProcess=false -cp c:\Users\nibberingc\.vscode\extensions\redhat.vscode-xml-0.10.1\server\org.eclipse.lsp4xml-uber.jar org.eclipse.lsp4xml.XMLServerLauncher
    0        9   23656           console-window-host (Windows internal process)
    0       31    2872         "C:\Users\nibberingc\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\nibberingc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=24780
    0       31   12932         "C:\Users\nibberingc\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\nibberingc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=24780
    0      220   21416         "C:\Program Files\WSO2\Enterprise Integrator\6.5.0\jdk\jdk8u212-b03\bin\java" -jar c:\Users\nibberingc\.vscode\extensions\sonarsource.sonarlint-vscode-1.15.0\server\sonarlint-ls.jar 50653 file:///c:/Users/nibberingc/.vscode/extensions/sonarsource.sonarlint-vscode-1.15.0/analyzers/sonarjava.jar file:///c:/Users/nibberingc/.vscode/extensions/sonarsource.sonarlint-vscode-1.15.0/analyzers/sonarjs.jar file:///c:/Users/nibberingc/.vscode/extensions/sonarsource.sonarlint-vscode-1.15.0/analyzers/sonarphp.jar file:///c:/Users/nibberingc/.vscode/extensions/sonarsource.sonarlint-vscode-1.15.0/analyzers/sonarpython.jar file:///c:/Users/nibberingc/.vscode/extensions/sonarsource.sonarlint-vscode-1.15.0/analyzers/sonarts.jar file:///c:/Users/nibberingc/.vscode/extensions/sonarsource.sonarlint-vscode-1.15.0/analyzers/sonarhtml.jar
    0      181   21108           node --max-old-space-size=2048 C:\Users\nibberingc\.sonarlint\work\.sonartmp_2686739648859054884\6817637340506597361\sonarts-bundle\node_modules\tslint-sonarts\bin\sonarts-server 50689
    0        9    2092             console-window-host (Windows internal process)
    0        9   21572           console-window-host (Windows internal process)
    0       53   21896         electron_node tsserver.js
    0       34   22812         electron_node server.js
   12     4091   25552         electron_node tsserver.js
    0       50   21548           electron_node typingsInstaller.js typesMap.js
    0        3    1132             C:\WINDOWS\system32\cmd.exe /d /s /c "npm install --ignore-scripts types-registry@latest"
    0       44   16516               "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" install --ignore-scripts types-registry@latest
    0       25    8744                 "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\update-notifier\check.js" "{\"pkg\":{\"name\":\"npm\",\"version\":\"6.12.1\"}}"
    0        9   23352               console-window-host (Windows internal process)
    0       13   18348     electron-crash-reporter
    0       70   22852     shared-process
    0      218   24924     gpu-process
    0       23   26064     utility

Workspace Stats:
|  Window (workflow.component.ts - workflow - Visual Studio Code)
|    Folder (workflow): 1552 files
|      File types: ts(362) html(320) js(232) scss(48) svg(38) json(34) map(8)
|                  css(7) png(6) md(5)
|      Conf files: package.json(7) tslint.json(3) tsconfig.json(2)
|                  launch.json(1)
|      Launch Configs: chrome

**Comment by mjbvz** [comment] 2020-03-04 23:40
Duplicate of https://github.com/microsoft/vscode/issues/85919

Try using VS Code 1.43+ (the current insiders build)

**Closed by mjbvz** 2020-03-04 23:40 UTC
