### ISSUE TITLE
Analysis in vscode not complete

### ISSUE THREAD

**Issue by TristanFAURE** [Microsoft/vscode-typescript-tslint-plugin#64] opened 2019-02-28 09:23 UTC
Hello when I run 
tslint -p myfolder_containing_tsconfig_json
I have several errors

When I open VSCode (1.31.1) with this plugin (1.0.0) I have less errors (the results are the same as 'tslint path_of_my_ts_file')

I have a tslint.json at the root of my folder and tsconfig.json in the same folder of the TS files. My vs code options are default ones

Is it normal ?

**Comment by mjbvz** [comment] 2019-03-02 01:36
Can you please provide an example of what errors are shown on the command line vs in the editor

**Comment by mjbvz** [comment] 2019-03-02 02:45
Duplicate of https://github.com/Microsoft/typescript-tslint-plugin/issues/61

**Comment by mjbvz** [comment] 2019-03-02 02:45
Please don't double post issues

**Closed by mjbvz** 2019-03-02 02:45 UTC
