### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by zsytssk** [microsoft/vscode-typescript-tslint-plugin#63] opened 2019-02-28 03:08 UTC
very slow sometime. It even cant work in some [project](https://github.com/zsytssk/test/tree/master/canvasTest) but the origin Tslint extension work normal.

**Comment by gauravmahto** [comment] 2019-03-01 08:47
Terribly slow.
Please find the attached gif.
![userprofiletsnodejsvisua](https://user-images.githubusercontent.com/3089767/53626817-bab28500-3c2c-11e9-82c7-48db9ddf004e.gif)
![userprofiletsnodejsvisua 1](https://user-images.githubusercontent.com/3089767/53626831-c605b080-3c2c-11e9-8149-9c5d05b5dcdc.gif)
![userprofiletsnodejsvisua 2](https://user-images.githubusercontent.com/3089767/53626840-cc942800-3c2c-11e9-80ac-2fa980488850.gif)

**Comment by oneillsp96** [comment] 2019-03-01 19:21
Same issue here.  Never had issue before the switch.

**Comment by mjbvz** [comment] 2019-03-02 02:35
Please provide more info about which version of VS Code you are on, your project setup, which other extensions you have installed,  and what is slow

**Comment by oneillsp96** [comment] 2019-03-04 14:45
Extensions: Partial Diff, Rainbow Brackets, vscode-typescript-tslint-plugin
VSCode Version: 1.3.1.1

webpack rule applied to .ts files:

 {
                    test: /\.tsx?$/,
                    use: [{ loader: "ts-loader", options: { transpileOnly: true, experimentalWatchApi: true } }],
                    exclude: /node_modules/,
 },

usersettings.json:

{
    "window.zoomLevel": 1,
    "php.validate.executablePath": "C:/Program Files/PHP/php.exe",
    "git.autofetch": true,
    "explorer.confirmDelete": false,
    "files.trimTrailingWhitespace": true,
    // "tslint.autoFixOnSave": true,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.fixAll.tslint": true
    },
    "breadcrumbs.enabled": true,
    "tslint.ignoreDefinitionFiles": true,
    "editor.fontFamily": "Consolas, 'Courier New', monospace, Operator Mono",
}

**Comment by oneillsp96** [comment] 2019-03-04 14:46
What is slow is the auto-fix on save functionality, which was almost instant with the old extension, and now takes 4-5 seconds

**Comment by oneillsp96** [comment] 2019-04-01 15:46
After disabling auto-save, the plugin is still unusably slow, errs out constantly, and causes me to have to restart Code every 10 minutes.  Decision now is ESLint with Typescript config, or back to the deprecated TSLint extension

**Comment by squidfunk** [comment] 2019-05-14 08:18
Same here. Unusably slow. Large files take ages to update, leading to race conditions with auto-fix on save where a change was made, the file is saved and TSLint having not caught up breaks the code.

**Comment by jesnil01** [comment] 2019-05-16 12:58
Same issue here. It's so slow I can't believe it.

**Comment by the-ult** [comment] 2019-05-17 10:32
Same here. Seems to be needing a lot of resources.

Especially slow while running/watching `ng serve app`

**Comment by squidfunk** [comment] 2019-05-17 10:44
Today, the [RC for TypeScript 3.5 was released](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/) talking about speed improvements in regard to [a regression introduced in 3.4](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/#speed-improvements):

> Unfortunately, as part of a bug fix in TypeScript 3.4 we accidentally introduced a regression that could lead to an explosion in how much work the type-checker did, and in turn, type-checking time. 

As VSCode currently uses 3.4 and this extension makes heavy use of the TypeScript server, it would explain the slowness. If this is true, we should see improvements with the next VSCode TypeScript dependency upgrade.

**Comment by mjbvz** [comment] 2019-05-22 00:09
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by Magn3s1um** [comment] 2020-03-20 18:10
Having the same issue with this.  Very slow, that everything turns to a crawl.  Sometimes, when I save, it doesn't recognize the changes fast enough and mangles the entire page.

Disabling the plugin resolves it.

Plugin Version: 1.2.3

```
Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by mjbvz** [comment] 2023-05-01 20:58
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

**Closed by mjbvz** 2023-05-01 20:58 UTC
