### ISSUE TITLE
Memory skyrocket

### ISSUE THREAD

**Issue by EonchGao** [microsoft/vscode-typescript-tslint-plugin#126] opened 2019-12-16 09:54 UTC
In vscode1.41.0, angular application CTRL +s, memory will skyrocket

**Comment by RonaldTheodoro** [comment] 2019-12-19 14:08
- VSCode Version: 1.41.0
- Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
- Date: 2019-12-12T20:13:03.044Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Ubuntu Linux x64 4.15.0-72-generic

Steps to Reproduce:

1. Open a *.ts file
2. Edit any part of the file


Does this issue occur when all extensions are disabled?: No

**Comment by darkpoetcc** [comment] 2019-12-20 15:44
This sounds somewhat similar to the issue sussed out here:  https://github.com/microsoft/vscode/issues/86723

**Comment by GitStorageOne** [comment] 2019-12-28 23:50
vscode 1.41.1
With only one plugin installed - TSLint (ms-vscode.vscode-typescript-tslint-plugin)  

simple angular component:
```typescript

import { Component } from '@angular/core';
import { ITest, createSomething } from '../test-bug/some-file';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  title = 'ng-lng-srvc';
  variable: ITest;

  somefunc() {
    createSomething();
  }

}
```

**some-file.ts**
```typescript

export function createSomething() {

}

export interface ITest {
  justOneMoreThing: string;
}

```

To reproduce fatal problem, we must quickly repeat described actions (few times):  
* delete `createSomething` from import section
* move cursor to `createSomething();` inside `somefunc` and use quickfix.

vscode will eat all available memory then crash.  
If plugin is disabled, everything will be fine.

**Comment by mjbvz** [comment] 2019-12-30 00:36
Duplicate of https://github.com/microsoft/vscode/issues/85919

**Closed by mjbvz** 2019-12-30 00:36 UTC
