### ISSUE TITLE
"TsLint: Fix all auto-fixable problems" not working in this plugin compared to the previous (TSLint (deprecated))

### ISSUE THREAD

**Issue by JGH153** [Microsoft/vscode-typescript-tslint-plugin#81] opened 2019-04-09 08:06 UTC
Recently switched to this plugin from the TSLint (deprecated). The problem is that all my TsLint command palet shortcuts like `TsLint: Fix all auto-fixable problems` are gone. 

Here is with the old and deprecated plugin:
![withDeprecated](https://user-images.githubusercontent.com/2571495/55783148-12ef6900-5aae-11e9-8ba2-4abed6cd44c4.png)

And here is with the new plugin:
![withNew](https://user-images.githubusercontent.com/2571495/55783150-12ef6900-5aae-11e9-8ea9-e8667744a8bd.png)

Using latest version of vscode 1.33.0, with the latest version of the plugins. Tried it across several computers with the same result. The project is in Angular, and i have tired using several different projects with the same result. There is no errors in the developer console.

Is the command `TsLint: Fix all auto-fixable problems`, or is this a bug? Has the command changed name, or been removed? Maybe the plugin is not running?

Let me know if you need any more information.

**Comment by mjbvz** [comment] 2019-04-09 18:43
Duplicate of #57

Will be in the next VS Code 1.34 insiders build. Action is called `Fix All`

**Closed by mjbvz** 2019-04-09 18:43 UTC
