### ISSUE TITLE
Disable rule on next line quick fix

### ISSUE THREAD

**Issue by villelahdenvuo** [Microsoft/vscode-typescript-tslint-plugin#21] opened 2018-11-14 11:27 UTC
The regular tslint plugin offers quick fixes to disable rules for specific lines, but it seems like this one doesn't.

**Comment by mjbvz** [comment] 2018-12-13 01:57
Can you please provide an example? https://github.com/Microsoft/typescript-tslint-plugin/issues/22 maybe?

**Comment by mjbvz** [comment] 2019-01-23 22:46
Closing as duplicate of Microsoft/typescript-tslint-plugin#22

**Closed by mjbvz** 2019-01-23 22:46 UTC
