### ISSUE TITLE
Whitespace error after @ in Angular declarators

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode-typescript-tslint-plugin#25] opened 2018-11-18 14:24 UTC
I've just started seeing lint errors (missing whitespace) for the @ in @component and such in an Angular application:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/13488/48673836-a3cfa300-eb13-11e8-884e-86706719d2bb.png">

**Comment by jtsom** [comment] 2018-11-18 14:38
This seems linked to the version of Typescript that is used. If the built-in version of VS Code Insiders issued (3.2.0-rc) the error shows. If switched to the project's version of Typescript (3.1.6), the error goes away.

**Comment by jtsom** [comment] 2018-11-18 15:17
Also seems related to the "whitespace": "check-type" rule.

**Comment by jtsom** [comment] 2018-11-27 13:37
Any movement on this issue? No updates to this plugin for a while...

**Comment by mjbvz** [comment] 2018-11-27 23:41
Duplicate of #24

**Closed by mjbvz** 2018-11-27 23:41 UTC
