### ISSUE TITLE
Format on save not working at all

### ISSUE THREAD

**Issue by vaindil** [microsoft/vscode-typescript-tslint-plugin#92] opened 2019-05-28 20:12 UTC
Expanding this from #76 because it seems to be a new issue. Format on save has stopped working entirely, not just depending on the command used. It happened both on 1.0.0 and 1.1.0 of the extension, my uninformed guess is that a VS Code change caused it.

**My version:**
Version: 1.35.0-insider (user setup)
Commit: a429fd13565d3392c87e31228ec9e8a2bf3708d5
Date: 2019-05-28T16:39:09.837Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Also reported on:**
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by mauricekleine** [comment] 2019-05-29 09:22
Same here. The action is also not showing in the 'Source Action' context menu.

**Comment by JerryGreen** [comment] 2019-05-30 08:44
Same here. I've tried to get back to `1.0.0` - it's working again. But `1.1.0` is broken :(

**Comment by mjbvz** [comment] 2019-06-17 23:03
Duplicate of #76

**Closed by mjbvz** 2019-06-17 23:03 UTC
