### ISSUE TITLE
Whitespace error in JSDoc

### ISSUE THREAD

**Issue by eppsilon** [Microsoft/vscode-typescript-tslint-plugin#24] opened 2018-11-16 17:05 UTC
Hi,

I'm seeing a "missing whitespace" error with code that looks like this:

```ts
const SOME_CONSTANT = 10;

/**
 * Maps an array of items to an array of their names.
 * @param arr A list of items.
 */
function func(arr: { name: string }[]) {
  return arr.map(item => item.name);
}
```

The error is on the first letter of `arr` in the JSDoc comment. Strangely it goes away if I remove the constant.

**Comment by mjbvz** [comment] 2018-11-17 01:58
Actually I can hit something like this if I have TS 3.1.4 installed in a workspace but an using VS Code TS version 3.2.0-rc. Potentially caused by Tslint using the wrong TS version

**Comment by eamodio** [comment] 2018-11-17 02:48
@mjbvz Yeah, I am seeing the same thing with almost the same setup -- TS 3.1.6 but vscode using TS 3.2.0-rc

**Comment by mjbvz** [comment] 2018-11-17 02:59
One case seems caused by 

```json
		"whitespace": [
			true,
			"check-type"
		]
```

Can't repo this using the command line version of TSLint yet, even installing 3.2.0-rc in workspace

**Comment by eamodio** [comment] 2018-11-17 03:06
Yeah, also:

```json
        "whitespace": [
            true,
            "check-rest-spread",
        ]
```

want code like:
```ts
...args
```

to be:
```ts
... args
```

And it doesn't matter if `check-rest-spread` is specified or not

**Comment by mjbvz** [comment] 2018-12-13 01:56
Upstream issue. This was supposed to be closed by https://github.com/Microsoft/typescript-tslint-plugin/commit/ee48c7f9e334440fb4a4ea9f3bbce423db360a15

**Closed by mjbvz** 2018-12-13 01:56 UTC
Labels: bug
