### ISSUE TITLE
vscode intellisense show wrong tip tslint not work

### ISSUE THREAD

**Issue by zsytssk** [microsoft/vscode-typescript-tslint-plugin#73] opened 2019-03-27 08:58 UTC
Issue Type: <b>Bug</b>

sometime after vscode work all day, ts file show wrong intellisense(other position code intellisense), and tslint not working, but ts file format work normally and js file intellisense lint work normlly. maybe is ts_lsp not update when file change...

Extension version: 1.0.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment] 2019-04-01 15:44
Please provide more information about what is not working. Screenshots and example code would also be helpful

**Comment by kevinbeaudoin** [comment] 2019-04-05 14:11
Sometimes we have the same issue when we change a lot of code at once or when prettier runs on a file.  In such cases we end up having tslint warning or issues indicator on wrong lines and extension seems to have stopped working.  We must relaunch vscode to fix the issue.  I can say we have to relaunch vscode at least once or twice a day since we've moved to the new tslint extension.

**Comment by davicoradini** [comment] 2019-04-06 15:42
same thing here (issues indicator in the wrong place, lost of suggestions), we all ended up removing the new extension and using the deprecated one, that works pretty well

really hard to reproduce though, as it works just fine for a period of time

*tip 1: the deprecated one also stops working after a while, but it takes a few seconds (5 or 7) and it starts working again, as for the new extension, when it stops, you need to restart vscode

*tip 2: I noticed same behavior even without any other extensions installed

**Comment by davicoradini** [comment] 2019-04-09 18:26
An example:
![image](https://user-images.githubusercontent.com/3173308/55825094-47295080-5ad3-11e9-881d-6e91cbb73a39.png)

Taking a closer look, it seems like vscode is highlighting it wrong too. Maybe it's related.

**Comment by nicholasrq** [comment] 2019-05-25 08:16
same here
<img width="421" alt="image" src="https://user-images.githubusercontent.com/767890/58366676-80c8e600-7ede-11e9-91f8-336a588715e0.png">

**Comment by nicholasrq** [comment] 2019-06-06 14:59
it becomes really annoying. type few characters -> restart ts lang -> type few more -> restart ts lang. it continues to break every time. we maybe need to address this issue to vscode team directly?

**Comment by zsytssk** [comment] 2019-06-10 09:18
It happened on vscode 1.35.0,
版本: 1.35.0 (user setup)
提交: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
日期: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by zsytssk** [comment] 2019-07-26 08:02
It occur more often(less than one minute) in latest vscode, very annoy; Are you still maintain this project ??, this bug make ts almost not useable!!!!
版本: 1.36.1 (user setup)
提交: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
日期: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

"tslint": "^5.18.0"
"typescript": "^3.5.3",

**Comment by zsytssk** [comment] 2019-07-26 08:48
maybe this is vscode bug, someone link this bug to vscode!
![TIM截图20190726160130](https://user-images.githubusercontent.com/2304648/61939160-35f24a00-afc5-11e9-8927-1c8cab7540d4.png)

**Comment by orta** [comment] 2019-07-26 15:38
It'd be great if we can get a re-production case for these

**Comment by mjbvz** [comment] 2023-05-01 20:58
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

**Closed by mjbvz** 2023-05-01 20:58 UTC
