### ISSUE TITLE
Move rule name from message to code in diagnostics

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-typescript-tslint-plugin#30] opened 2018-12-13 07:57 UTC
![image](https://user-images.githubusercontent.com/261509/49923741-176b9280-febd-11e8-8dce-6081a389bbdf.png)

The code is currently displaying as `1` for all problems.

Similar change for my own extension [here](https://github.com/glen-84/vscode-sass-lint/commit/4c9da188bf6be28c3480ad66d345c7668c7db9c3).

**Comment by mjbvz** [comment] 2019-01-23 22:47
Duplicate of https://github.com/Microsoft/typescript-tslint-plugin/issues/16

**Closed by mjbvz** 2019-01-23 22:47 UTC
