### ISSUE TITLE
TSLint trying to lint any JS file

### ISSUE THREAD

**Issue by mauroavidbots** [Microsoft/vscode-typescript-tslint-plugin#29] opened 2018-12-10 21:12 UTC
Hello all!

After I installed the vscode-typescript-tslint-plugin, I am having this problem where all the .js files starts with the following error:

```
Failed to load the TSLint library for the document path/to/javascript/file.js
To use TSLint for single file install tslint globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen VS Code after installing tslint. [1]
```

This happens to all .js files, including in projects without tslint.json. 

I've already checked the `tslint.jsEnable` and it is set to false. 

I'm currently using the vscode-typescript-tslint-plugin@0.1.1 with vscode@1.29.1. I have the tslint installed in the workspace, but not globally.

Thanks!

**Comment by mjbvz** [comment] 2018-12-13 01:57
Duplicate of #26

**Closed by mjbvz** 2018-12-13 01:57 UTC
Labels: bug
